# Generated by Django 6.1.1 on 2026-10-07 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activitylog_category_department_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
